# languageCode = "ja"
# languageName = "Japanese"
# disabled = false
locale = "ja"
label = "Japanese"
weight = 3
title = "光monの静的ブログ"

[params]
  displayName = "日本語"
  isoCode = "ja"
  rtl = false
  dateFormat = "2006年1月2日"
  # logo = "img/logo.png"
  # secondaryLogo = "img/secondary-logo.png"
  # description = "My awesome website"
  # copyright = "Copy, _right?_ :thinking_face:"

[params.author]
name = "lightmon"
email = "lightmon5210@outlook.com"
image = "img/author.jpg"
headline = "少女祈祷中……"
bio = "管理人が怠けているため、まだプロフィールはありません。"
links = [
  { twitter = "https://x.com/lightmon5210" },
  { github = "https://github.com/lightmon233" },
  { email = "lightmon5210@outlook.com"}
]

